#!/usr/bin/env python
import sys
#import bsddb
from bsddb3 import db
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    if not isAscii(str):
	return convertToHex(str)
    return str

def fformat(str):
    result = "%s : " % str[1:ord(str[0])+1]
    for ch in str[ord(str[0])+2:]:
	result += ("%02x" % ord(ch))
    result += '  '
    for ch in str[ord(str[0])+2:]:
	if ord(ch) < 128 and ord(ch) > 32:
	    result += ch
	else:
	    result += '.'

    return result


wallet = db.DB()
wallet.open("WWWWWWWW.dat", "main", db.DB_BTREE)
keys = wallet.keys()
for k in keys:
    print(fformat(k))
#    print(bdb[k])
print len(keys)
wallet.close()
