#!/usr/bin/env python
import sys
import plyvel
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    #if not isAscii(str):
    return convertToHex(str)
    return str

if len(sys.argv) != 2:
    print 'usage: ', os.path.basename(os.path.normpath(sys.argv[0])), ' database'
    sys.exit()


counts = []
for i in range(0,255):
    counts.append(0)

db = plyvel.DB(sys.argv[1])
for key,value in db:
    counts[ord(key[0])] += 1
    if key[0] == chr(0x0e):
	print "%s : %s" % (format(key),format(value))
	
db.close()

for i in range(0,255):
    if counts[i] != 0:
        print "0x%02X|%s: %d" % (i,chr(i),counts[i])




