#!/usr/bin/env python

import sys
import time
import json
import requests
from base64 import b64encode
import unicodedata

auth = b64encode(b"beach:surf")
headers = {'content-type': 'text/plain;',"Authorization":"Basic %s" % auth}
url = 'http://127.0.0.1:7000'
id = 0

def dot():
	sys.stdout.write('.')
	sys.stdout.flush()

def normalize(value):
	str = "%.9f" % value
	return float(str)

def send(data):
	global id
	data["id"] = id
	id += 1
	print data
	response = requests.post(url,data=json.dumps(data),headers=headers)
	if response.status_code != 200:
		raise Exception('HTTP Error code: %s' % response.status_code)
	if response.json()["result"] == None:
		raise Exception('Command error: %s(%s)' % response.json()["error"]["message"] %  response.json()["error"]["code"])
	return response.json()["result"]



def blockCount(): 
	res = send({"method":"getblockcount","params":[]}) 
	return int(res)


def z_balance(address,minconf=1):
	res = send({"method":"z_getbalance","params":[address,minconf]})  
	return float(res)

def z_totalBalance(minconf=1):
	res = send({"method":"z_gettotalbalance","params":[minconf]})  
	return {"transparent":float(res["transparent"]),"private":float(res["private"]),"total":float(res["total"])}

def z_newaddress():
	res = send({"method":"z_getnewaddress","params":[]}) 
	return res.encode('utf-8')

def t_newaddress():
	res = send({"method":"getnewaddress","params":[]}) 
	return res.encode('utf-8')

def spend(amount,minconf=1):
	taddr = t_newaddress()
	res = send({"method":"sendfrom","params":["",taddr,amount,minconf,False,"",""]})
	print taddr 
	while z_balance(taddr) == 0.0:
		dot()
		time.sleep(5)
	print '\n'
	return taddr,res.encode('utf-8')

def z_spend(source,amount,minconf=1):
	zaddr = z_newaddress()
	opid = send({"method":"z_sendmany","params":[source,[{"address":zaddr,"amount":amount}]]})
	print opid
	return zaddr, opid




#### send({"method":"z_sendmany"})




####,"params":[source,[{"address":zaddr,"amount":amount}]]})
#	print opid," : ",zaddr 
#	print '\n'
#	return zaddr

def shield(amount):
	taddr, txid = spend(normalize(amount + 0.0001))
	zaddr, opid = z_spend(taddr,amount)	
	return [taddr,zaddr]


print blockCount()
print z_balance("yZyJG8SKBW6B4sRDmjPYZ8NWqGAXNon25e")
print z_totalBalance()
print shield(3.33333)
#print spend(10.01)
