#!/usr/bin/env python
from __future__ import print_function

import sys
import os
import time
import json
import requests
from base64 import b64encode
import unicodedata

auth = b64encode(b"beach:surf")
headers = {'content-type': 'text/plain;',"Authorization":"Basic %s" % auth}
url = 'http://127.0.0.1:7000'
id = 0

def dot():
	sys.stdout.write('.')
	sys.stdout.flush()

def normalize(value):
	str = "%.9f" % value
	return float(str)

def send(data,display=False):
	global id
	data["id"] = id
	id += 1
	if display:
		print(data)
	response = requests.post(url,data=json.dumps(data),headers=headers)
	if response.status_code != 200:
		raise Exception('HTTP Error code: %s' % response.status_code)
	if response.json()["result"] == None:
		raise Exception('Command error: %s(%s)' % response.json()["error"]["message"] %  response.json()["error"]["code"])
	return response.json()["result"]


def blockCount(): 
	res = send({"method":"getblockcount","params":[]}) 
	return int(res)

def blockhash(index):
	res =  send({"method":"getblockhash","params":[index]}) 
	return res

def block(hash):
	res =  send({"method":"getblock","params":[hash]}) 
	return res

def txHasJS(hash):
	res =  send({"method":"getrawtransaction","params":[hash,1]})
	return len(res["vjoinsplit"]) > 0

def getAllJS():
	res =  send({"method":"dtg2","params":[]})
	return res

#if len(sys.argv) != 2:
#    print ('usage: ', os.path.basename(os.path.normpath(sys.argv[0])), '<start>')
#    sys.exit()


allJS = getAllJS()
print(len(allJS))

for tx in allJS:
	print(tx["txid"])




'''
bcount = blockCount()

for i in range(int(sys.argv[1]),bcount):
	h = blockhash(i)
	b = block(h)
	transactions = b["tx"]
	for tx in transactions:
		try:
			if txHasJS(tx.encode('utf-8')):
				print(tx)
		except:
			continue
'''			
