#!/usr/bin/env python
import sys
#import bsddb
from bsddb3 import db
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    if not isAscii(str):
	return convertToHex(str)
    return str

def fformat(str):
    result = "%s : " % str[1:ord(str[0])+1]
    for ch in str[ord(str[0])+2:]:
	result += ("%02x" % ord(ch))
    result += '  '
    for ch in str[ord(str[0])+2:]:
	if ord(ch) < 128 and ord(ch) > 32:
	    result += ch
	else:
	    result += '.'

    return result

def key(str):
    return  str[1:ord(str[0])+1]


def showString(id):
    global wallet
    for k,v in wallet:
    	print "%s: %s" % (k,v)

def filter(cur,str):
    rec = cur.first()
    while rec:
	if key(rec[0]) == str:
            print "%s" % (fformat(rec[0]))
        rec = cur.next()	

if len(sys.argv) != 3:
    print 'usage: ', os.path.basename(os.path.normpath(sys.argv[0])), '<database> <string>'
    sys.exit()

wallet = db.DB()
wallet.open(sys.argv[1], "main", db.DB_BTREE)
cur = wallet.cursor()

filter(cur,sys.argv[2])

cur.close()
wallet.close()
