#!/usr/bin/env python
import sys
#import bsddb
from bsddb3 import db
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    if not isAscii(str):
	return convertToHex(str)
    return str

def fformat(str):
    result = "%s : " % str[1:ord(str[0])+1]
    for ch in str[ord(str[0])+2:]:
	result += ("%02x" % ord(ch))
    result += '  '
    for ch in str[ord(str[0])+2:]:
	if ord(ch) < 128 and ord(ch) > 32:
	    result += ch
	else:
	    result += '.'

    return result

def key(str):
    return  str[1:ord(str[0])+1]


def showString(id):
    global wallet
    for k,v in wallet:
    	print "%s: %s" % (k,v)
	

if len(sys.argv) != 2:
    print 'usage: ', os.path.basename(os.path.normpath(sys.argv[0])), '<database>'
    sys.exit()

wallet = db.DB()
wallet.open(sys.argv[1], "main", db.DB_BTREE)
keys = wallet.keys()
list = {}
for k in keys:
    sk = key(k)
    if sk in list:
        list[sk] += 1
    else:
    	list[sk] = 1
for k in list:
    	print "%s: %d" % (k,list[k])

print len(keys)

sss = wallet.stat()
print sss['version']
print sss
#showString('name')

wallet.close()
