#!/usr/bin/env python
import sys
import plyvel
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    if not isAscii(str):
	return convertToHex(str)
    return str

if len(sys.argv) < 2 or len(sys.argv) > 4:
    print 'usage: ', os.path.basename(os.path.normpath(sys.argv[0])), ' database [start] [number]'
    sys.exit()

start = 0
number = 10

if len(sys.argv) > 2:
    start = int(sys.argv[2])

if len(sys.argv) > 3:
    number = int(sys.argv[3])

db = plyvel.DB(sys.argv[1])
count = 0
for key,value in db:
    if count >= start and count < start + number:
	print "%08d: %s : %s" % (count,format(key),format(value))
    count+=1
print(count)
db.close()

