#!/usr/bin/env python
import sys
import plyvel
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    #if not isAscii(str):
    return convertToHex(str)
    return str

if len(sys.argv) != 3:
    print 'usage: ', os.path.basename(os.path.normpath(sys.argv[0])), ' <database> <letter>'
    sys.exit()

db = plyvel.DB(sys.argv[1])
count = 0
letter = ord(sys.argv[2])
for key,value in db:
    if ord(key[0]) != letter:
	print "%08d(%s): %s : %s" % (count,key[0],format(key),format(value))
    	count+=1
print(count)
db.close()
