#!/usr/bin/env python
import sys
import plyvel
import os

def convertToHex(str):
    return ''.join(x.encode('hex') for x in str)

def isAscii(str):
    return all(ord(c)<128 for c in str)

def format(str):
    if not isAscii(str):
	return convertToHex(str)
    return str

if len(sys.argv) != 3:
    print 'usage: ', os.path.basename(os.path.normpath(sys.argv[0])), ' database txid'
    sys.exit()

db = plyvel.DB(sys.argv[1]) 

entry = db.get(sys.argv[2].decode("hex")) # ,b'No such transaction')
if entry != None:
    print convertToHex(entry)
else:
    print 'No such transaction'


db.close()

